services:
  - type: web
    name: nebulacore
    env: php
    plan: free
    region: singapore
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      chmod -R 755 storage bootstrap/cache
    startCommand: php artisan serve --host=0.0.0.0 --port=8000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false